# Generated by Django 2.1.1 on 2020-01-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
