# Generated by Django 2.1.5 on 2020-01-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200112_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['-is_main', '-scope']},
        ),
    ]
