# Generated by Django 2.1.5 on 2020-01-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200112_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['-is_main', 'scope']},
        ),
    ]
